### ISSUE TITLE
process.stdout.cursorTo is not a function

### ISSUE THREAD

**Issue by gasolin** [holepunchto/bare-process#2]
to run in pear dev:

```
import process from 'bare-process'
const { stdin, stdout, exit } = process;
```

was got 

`process.stdout.cursorTo is not a function`
or
`stdin.setEncoding is not a function`

**Comment by kasperisager** [comment]
There are two separate things here:

1. `bare-tty` does not support any of the ANSI escape methods that the Node.js `tty` module implements. Instead, https://github.com/holepunchto/bare-ansi-escapes should be used.
2. `bare-stream`, which reexports `streamx`, does not support the `setEncoding` method. Instead, the buffers read should be stringified using `buffer.toString([encoding])`.
